#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Aug 22, 2023 11:57:24 AM SAST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import re
import Main

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = Main.Toplevel1(_top1)
    root.mainloop()

def calculate_strength():
    password = Entry1.get()  # Replace entry1 with the actual Entry widget name

    # Calculate password strength (example: simple logic based on length)
    strength = min(len(password) / 12, 1.0)

    # Update the progress bar
    progress_value = int(strength * 100)
    tprogressbar1["value"] = progress_value  # Replace tprogressbar1 with the actual Progressbar widget name

    # You can also customize the appearance of the progress bar based on the strength value
    if strength >= 0.8:
        tprogressbar1["style"] = "TProgressbar"
    elif strength >= 0.5:
        tprogressbar1["style"] = "TProgressbar.Horizontal.TProgressbar"
    else:
        tprogressbar1["style"] = "TProgressbar.Horizontal.Warning.TProgressbar"

    # You can also update the Label4 text based on the strength value
    label4["text"] = f"Password Strength (Ensure that it is full!): {progress_value}%"

if __name__ == '__main__':
    Main.start_up()




